# Generated by Django 3.0b1 on 2019-11-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(default='movie title', max_length=100)),
                ('movie_release_year', models.CharField(default='year', max_length=10)),
                ('imbd_link', models.CharField(default='imdb link', max_length=200)),
                ('movie_poster', models.CharField(default='link to poster or pic', max_length=200)),
                ('movie_quote', models.TextField(default='quote here')),
            ],
        ),
    ]
