# Generated by Django 3.0b1 on 2019-11-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(default='movie title', max_length=100)),
                ('movie_release_year', models.CharField(default='year', max_length=10)),
                ('imbd_link', models.CharField(default='imdb link or url', max_length=200)),
                ('movie_poster', models.CharField(default='link to poster or pic', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='quote',
            name='imbd_link',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='movie_poster',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='movie_release_year',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='movie_title',
        ),
    ]
