# Generated by Django 3.0b1 on 2019-11-06 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_quotes', '0002_auto_20191106_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='title',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='movie_quotes.Movie'),
            preserve_default=False,
        ),
    ]
